"""Initial schema

Revision ID: e2a230e962cb
Revises: 
Create Date: 2026-07-16 15:35:06.145852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a230e962cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('short_term_gains', sa.Float(), nullable=True),
    sa.Column('short_term_losses', sa.Float(), nullable=True),
    sa.Column('long_term_gains', sa.Float(), nullable=True),
    sa.Column('long_term_losses', sa.Float(), nullable=True),
    sa.Column('harvested_losses', sa.Float(), nullable=True),
    sa.Column('estimated_tax_liability', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('metrics_daily_strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('gross_pnl', sa.Float(), nullable=True),
    sa.Column('net_pnl', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('short_term_realized', sa.Float(), nullable=True),
    sa.Column('long_term_realized', sa.Float(), nullable=True),
    sa.Column('fees_total', sa.Float(), nullable=True),
    sa.Column('slippage_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('headline', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('impact_tag', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('open_timestamp', sa.DateTime(), nullable=False),
    sa.Column('close_timestamp', sa.DateTime(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('tags', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_entry', sa.DateTime(), nullable=False),
    sa.Column('timestamp_exit', sa.DateTime(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('gross_pnl', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=True),
    sa.Column('slippage', sa.Float(), nullable=True),
    sa.Column('net_pnl', sa.Float(), nullable=True),
    sa.Column('holding_period_seconds', sa.Integer(), nullable=True),
    sa.Column('is_short_term', sa.Boolean(), nullable=True),
    sa.Column('is_long_term', sa.Boolean(), nullable=True),
    sa.Column('rule_break_flag', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('positions')
    op.drop_table('portfolios')
    op.drop_table('news_items')
    op.drop_table('metrics_daily_strategy')
    op.drop_table('tickers')
    op.drop_table('tax_summaries')
    op.drop_table('strategies')
    # ### end Alembic commands ###
